name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > myKey.pem
          chmod 600 myKey.pem

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i myKey.pem ubuntu@${{ secrets.ELASTIC_IP }} "echo Connected Successfully!"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i myKey.pem ubuntu@${{ secrets.ELASTIC_IP }} << 'EOF'
            set -e
            
            # Update system packages and upgrade system packages
            sudo apt update && sudo apt upgrade -y


            # Clone repository if it doesn't exist, otherwise pull latest changes
            if [ ! -d ".git" ]; then
            git clone https://github.com/RyanByrne03/CadCAV2 DiaryApp
            else
            git pull origin main
            fi

            # Navigate to the application directory
            cd /home/ubuntu/DiaryApp

            # Ensure proper ownership of the directory and its contents
            sudo chown -R ubuntu:ubuntu /home/ubuntu/DiaryApp

            # Clean up existing bundle directory to fix permissions
            sudo rm -rf vendor/bundle

            # Ensure Bundler is installed
            gem install bundler -v 2.6.1

            # Install application dependencies
            bundle _2.6.1_ install 

            # Run database migrations
            bundle exec rails db:migrate

            # Kill any existing Rails server
            pkill -f "rails server" || true
            # Start the Rails server
            bundle exec rails server -d -b 0.0.0.0 -p 3000

            echo "Deployment Complete!"
          EOF

      - name: Clean up
        run: |
          rm -f myKey.pem