name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > myKey.pem
          chmod 600 myKey.pem

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i myKey.pem ubuntu@${{ secrets.ELASTIC_IP }} "echo Connected Successfully!"

      - name: Deploy to EC2
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_M_KEY }}
        run: |
          # Write the master key to a local file
          echo -n "$RAILS_MASTER_KEY" > master.key
          
          # Copy the master key to the server
          scp -o StrictHostKeyChecking=no -i myKey.pem master.key ubuntu@${{ secrets.ELASTIC_IP }}:/tmp/master.key
          
          # Run the deployment script
          ssh -o StrictHostKeyChecking=no -i myKey.pem ubuntu@${{ secrets.ELASTIC_IP }} << 'EOF'
            set -e
            
            # Update system packages and install required dependencies
            sudo apt-get update -y
            sudo apt-get install -y build-essential libssl-dev zlib1g-dev git curl

            # Install Rails 7.2.2.1
            gem install rails -v 7.2.2.1

            # Create app directory if it doesn't exist
            sudo mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app
          
            # Ensure proper ownership
            sudo chown -R ubuntu:ubuntu /home/ubuntu/app
          
            # Clone repository if it doesn't exist, otherwise pull latest changes
            if [ ! -d ".git" ]; then
              git clone https://github.com/RyanByrne03/CadCAV2 . 
            else
              git pull origin main
            fi
          
            # Install Bundler
            sudo gem install bundler -v 2.6.1

            # Install gems
            bundle _2.6.1_ install
          
            # Set up Rails environment
            export RAILS_ENV=production
          
            # Set up master key
            mkdir -p config
            mv /tmp/master.key config/master.key
            chmod 600 config/master.key
          
            # Clean up any existing credentials
            rm -f config/credentials.yml.enc
            rm -f config/credentials/production.yml.enc
            
            # Generate new credentials
            EDITOR="/bin/true" bundle exec rails credentials:edit
          
            # Database setup
            bundle exec rails db:migrate RAILS_ENV=production
          
            # Precompile assets
            bundle exec rails assets:precompile
          
            # Kill any existing Rails server
            pkill -f "rails server" || true
          
            # Start the Rails server
            bundle exec rails server -d -b 0.0.0.0 -p 3000
          
            echo "Deployment Complete!"
          EOF

      - name: Clean up
        run: |
          rm -f myKey.pem
